### ISSUE TITLE
Patch doesn't seem to have been applied

### ISSUE THREAD

**Issue by waderyan** [jrieken/gulp-tsb#37]
I nuked my `node_modules` folder and re installed to get `gulp-tsb` version 1.10.2. I see the same issue that #33 was supposed to fix. 

This is what `lib/index.js` looks like in my `node_modules` folder. 

```js
function create(configOrName, verbose, json, onError) {
    var config;
    if (typeof configOrName === 'string') {
        var parsed = typescript_1.readConfigFile(configOrName, function (path) { return fs_1.readFileSync(path, undefined); });
        if (parsed.error) {
            console.error(parsed.error);
            return function () { return null; };
        }
        config = parsed.config.compilerOptions;
    }
```

Changing `undefined` to `'utf-8'` solves the breaking error. Here is the error message I was seeing. 

```
[09:40:07] TypeError: Cannot read property 'on' of null
    at DestroyableTransform.Readable.pipe (/Users/waander/Development/Microsoft/vscode-docs/out/vscode-website/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:516:7)
    at Gulp.<anonymous> (/Users/waander/Development/Microsoft/vscode-docs/out/vscode-website/gulpfile.js:110:10)
    at module.exports (/Users/waander/Development/Microsoft/vscode-docs/out/vscode-website/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/waander/Development/Microsoft/vscode-docs/out/vscode-website/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/waander/Development/Microsoft/vscode-docs/out/vscode-website/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/waander/Development/Microsoft/vscode-docs/out/vscode-website/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:20
    at nextTickCallbackWith0Args (node.js:419:9)
    at process._tickCallback (node.js:348:13)
    at Function.Module.runMain (module.js:444:11)
```

**Comment by waderyan** [comment]
Working now :)
