### ISSUE TITLE
New Release/Update vinyl dependency to >= 0.5.3

### ISSUE THREAD

**Issue by AdamWillden** [jrieken/gulp-tsb#77]
The [latest PR](https://github.com/jrieken/gulp-tsb/commit/45b7c8ad8ba4d8117ad9052b930ab2fe14e89875) already fixed what I'm after but there's not been a release since. Any chance of a published release?

The issue I'm facing is as follows:

```
[13:06:12] Error: Received a non-Vinyl object in `dest()`
    at DestroyableTransform.normalize [as _transform] (C:\Documents\Repos\oi\siopa-package-tools\node_modules\vinyl-fs\lib\dest\prepare.js:16:17)
    at DestroyableTransform.Transform._read (C:\Documents\Repos\oi\siopa-package-tools\node_modules\readable-stream\lib\_stream_transform.js:182:10)
    at DestroyableTransform.Transform._write (C:\Documents\Repos\oi\siopa-package-tools\node_modules\readable-stream\lib\_stream_transform.js:170:83)
    at doWrite (C:\Documents\Repos\oi\siopa-package-tools\node_modules\readable-stream\lib\_stream_writable.js:406:64)
    at writeOrBuffer (C:\Documents\Repos\oi\siopa-package-tools\node_modules\readable-stream\lib\_stream_writable.js:395:5)
    at DestroyableTransform.Writable.write (C:\Documents\Repos\oi\siopa-package-tools\node_modules\readable-stream\lib\_stream_writable.js:322:11)
    at Pumpify.Duplexify._write (C:\Documents\Repos\oi\siopa-package-tools\node_modules\duplexify\index.js:212:22)
    at doWrite (C:\Documents\Repos\oi\siopa-package-tools\node_modules\readable-stream\lib\_stream_writable.js:406:64)
    at writeOrBuffer (C:\Documents\Repos\oi\siopa-package-tools\node_modules\readable-stream\lib\_stream_writable.js:395:5)
    at Pumpify.Writable.write (C:\Documents\Repos\oi\siopa-package-tools\node_modules\readable-stream\lib\_stream_writable.js:322:11)
[13:06:12] 'buildTsEs2015' errored after 1.62 s
```

~~Hi,~~

~~Not really investigated this but I'm running into an issue when using gulp 4.0 and I think it's due to the following (from [gulpjs/vinyl-fs](https://github.com/gulpjs/vinyl-fs/issues/288#issuecomment-355352227 )):~~

> yes, it was intentional because those versions are missing critical parts to the ecosystem. Vinyl 0.5.3 came with gulp-util, so that's what most people would be using. I might have been able to slip a 0.4.6 -> 0.5.3 change into vinyl-source-stream but I want people to upgrade to 2.0.0 so I don't really care to do that now.

~~I've not looked into this in any detail. Could the dependency be updated to at least 0.5.3?~~

**Comment by jrieken** [comment]
This is now fixed
