### ISSUE TITLE
Build with latest typescript throws errors 

### ISSUE THREAD

**Issue by vivekkj123** [jrieken/gulp-tsb#84]
```
gulp build
[06:32:22] Local gulp not found in /<<PKGBUILDDIR>>
[06:32:22] Try running: npm install gulp
[06:32:22] Using globally installed gulp
"No inputs were found in config file 'tsconfig.json'. Specified 'include' paths were '[\"src\"]' and 'exclude' paths were '[\"lib/\"]'."
[06:32:22] Using gulpfile /<<PKGBUILDDIR>>/gulpfile.js
[06:32:22] Starting 'build'...
[06:32:22] Starting 'pre-build'...
[06:32:22] Finished 'pre-build' after 8.19 ms
[06:32:22] Starting 'buildWithPreBuild'...
[06:32:22] 'buildWithPreBuild' errored after 967 μs
[06:32:22] Error: Cannot find module './lib-prebuild'
Require stack:
- /<<PKGBUILDDIR>>/gulpfile.js
- /usr/share/nodejs/gulp-cli/lib/versioned/^4.0.0/index.js
- /usr/share/nodejs/gulp-cli/index.js
- /usr/share/nodejs/gulp/bin/gulp.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.resolve (internal/modules/cjs/helpers.js:80:19)
    at reload (/<<PKGBUILDDIR>>/gulpfile.js:62:22)
    at buildWithPreBuild (/<<PKGBUILDDIR>>/gulpfile.js:28:15)
    at bound (domain.js:427:14)
    at runBound (domain.js:440:12)
    at asyncRunner (/usr/share/nodejs/gulp/node_modules/async-done/index.js:55:18)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
[06:32:22] 'build' errored after 11 ms
```

**Comment by vivekkj123** [comment]
@jrieken
